package model_Service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 17 17:34:36 IST 2021
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void takeAttendence(String d);

    void SalaryRaise(int i);

    void marksEntry(String Exam, String Class);
}
