package model_Service.client;

import model_Service.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 17 17:34:36 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void takeAttendence(String d) {
        Object _ret =
            this.riInvokeExportedMethod(this,"takeAttendence",new String [] {"java.lang.String"},new Object[] {d});
        return;
    }

    public void SalaryRaise(int i) {
        Object _ret =
            this.riInvokeExportedMethod(this,"SalaryRaise",new String [] {"int"},new Object[] {new Integer(i)});
        return;
    }

    public void marksEntry(String Exam, String Class) {
        Object _ret =
            this.riInvokeExportedMethod(this,"marksEntry",new String [] {"java.lang.String","java.lang.String"},new Object[] {Exam, Class});
        return;
    }
}
