package model_Entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 13 08:26:12 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaffEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        StaffId {
            public Object get(StaffEOImpl obj) {
                return obj.getStaffId();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setStaffId((Number)value);
            }
        }
        ,
        FullName {
            public Object get(StaffEOImpl obj) {
                return obj.getFullName();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setFullName((String)value);
            }
        }
        ,
        FatherName {
            public Object get(StaffEOImpl obj) {
                return obj.getFatherName();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setFatherName((String)value);
            }
        }
        ,
        Dateofbirth {
            public Object get(StaffEOImpl obj) {
                return obj.getDateofbirth();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setDateofbirth((Date)value);
            }
        }
        ,
        Gender {
            public Object get(StaffEOImpl obj) {
                return obj.getGender();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setGender((String)value);
            }
        }
        ,
        Phone {
            public Object get(StaffEOImpl obj) {
                return obj.getPhone();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setPhone((Number)value);
            }
        }
        ,
        Email {
            public Object get(StaffEOImpl obj) {
                return obj.getEmail();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setEmail((String)value);
            }
        }
        ,
        Aadhaar {
            public Object get(StaffEOImpl obj) {
                return obj.getAadhaar();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setAadhaar((Number)value);
            }
        }
        ,
        Address {
            public Object get(StaffEOImpl obj) {
                return obj.getAddress();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setAddress((String)value);
            }
        }
        ,
        Salary {
            public Object get(StaffEOImpl obj) {
                return obj.getSalary();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setSalary((Number)value);
            }
        }
        ,
        Photo {
            public Object get(StaffEOImpl obj) {
                return obj.getPhoto();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setPhoto((BlobDomain)value);
            }
        }
        ,
        JoinDate {
            public Object get(StaffEOImpl obj) {
                return obj.getJoinDate();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setJoinDate((Date)value);
            }
        }
        ,
        EducationalQualification {
            public Object get(StaffEOImpl obj) {
                return obj.getEducationalQualification();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setEducationalQualification((String)value);
            }
        }
        ,
        Subject {
            public Object get(StaffEOImpl obj) {
                return obj.getSubject();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setSubject((String)value);
            }
        }
        ,
        SubjectEO {
            public Object get(StaffEOImpl obj) {
                return obj.getSubjectEO();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setSubjectEO((EntityImpl)value);
            }
        }
        ,
        TeacherClassEO {
            public Object get(StaffEOImpl obj) {
                return obj.getTeacherClassEO();
            }

            public void put(StaffEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(StaffEOImpl object);

        public abstract void put(StaffEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int STAFFID = AttributesEnum.StaffId.index();
    public static final int FULLNAME = AttributesEnum.FullName.index();
    public static final int FATHERNAME = AttributesEnum.FatherName.index();
    public static final int DATEOFBIRTH = AttributesEnum.Dateofbirth.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int PHONE = AttributesEnum.Phone.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int AADHAAR = AttributesEnum.Aadhaar.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int SALARY = AttributesEnum.Salary.index();
    public static final int PHOTO = AttributesEnum.Photo.index();
    public static final int JOINDATE = AttributesEnum.JoinDate.index();
    public static final int EDUCATIONALQUALIFICATION = AttributesEnum.EducationalQualification.index();
    public static final int SUBJECT = AttributesEnum.Subject.index();
    public static final int SUBJECTEO = AttributesEnum.SubjectEO.index();
    public static final int TEACHERCLASSEO = AttributesEnum.TeacherClassEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StaffEOImpl() {
    }

    /**
     * Gets the attribute value for StaffId, using the alias name StaffId.
     * @return the StaffId
     */
    public Number getStaffId() {
        return (Number)getAttributeInternal(STAFFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StaffId.
     * @param value value to set the StaffId
     */
    public void setStaffId(Number value) {
        setAttributeInternal(STAFFID, value);
    }

    /**
     * Gets the attribute value for FullName, using the alias name FullName.
     * @return the FullName
     */
    public String getFullName() {
        return (String)getAttributeInternal(FULLNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FullName.
     * @param value value to set the FullName
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**
     * Gets the attribute value for FatherName, using the alias name FatherName.
     * @return the FatherName
     */
    public String getFatherName() {
        return (String)getAttributeInternal(FATHERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FatherName.
     * @param value value to set the FatherName
     */
    public void setFatherName(String value) {
        setAttributeInternal(FATHERNAME, value);
    }

    /**
     * Gets the attribute value for Dateofbirth, using the alias name Dateofbirth.
     * @return the Dateofbirth
     */
    public Date getDateofbirth() {
        return (Date)getAttributeInternal(DATEOFBIRTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dateofbirth.
     * @param value value to set the Dateofbirth
     */
    public void setDateofbirth(Date value) {
        setAttributeInternal(DATEOFBIRTH, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the Gender
     */
    public String getGender() {
        return (String)getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for Phone, using the alias name Phone.
     * @return the Phone
     */
    public Number getPhone() {
        return (Number)getAttributeInternal(PHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Phone.
     * @param value value to set the Phone
     */
    public void setPhone(Number value) {
        setAttributeInternal(PHONE, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the Email
     */
    public String getEmail() {
        return (String)getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for Aadhaar, using the alias name Aadhaar.
     * @return the Aadhaar
     */
    public Number getAadhaar() {
        return (Number)getAttributeInternal(AADHAAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Aadhaar.
     * @param value value to set the Aadhaar
     */
    public void setAadhaar(Number value) {
        setAttributeInternal(AADHAAR, value);
    }

    /**
     * Gets the attribute value for Address, using the alias name Address.
     * @return the Address
     */
    public String getAddress() {
        return (String)getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Address.
     * @param value value to set the Address
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for Salary, using the alias name Salary.
     * @return the Salary
     */
    public Number getSalary() {
        return (Number)getAttributeInternal(SALARY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salary.
     * @param value value to set the Salary
     */
    public void setSalary(Number value) {
        setAttributeInternal(SALARY, value);
    }

    /**
     * Gets the attribute value for Photo, using the alias name Photo.
     * @return the Photo
     */
    public BlobDomain getPhoto() {
        return (BlobDomain)getAttributeInternal(PHOTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Photo.
     * @param value value to set the Photo
     */
    public void setPhoto(BlobDomain value) {
        setAttributeInternal(PHOTO, value);
    }

    /**
     * Gets the attribute value for JoinDate, using the alias name JoinDate.
     * @return the JoinDate
     */
    public Date getJoinDate() {
        return (Date)getAttributeInternal(JOINDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for JoinDate.
     * @param value value to set the JoinDate
     */
    public void setJoinDate(Date value) {
        setAttributeInternal(JOINDATE, value);
    }

    /**
     * Gets the attribute value for EducationalQualification, using the alias name EducationalQualification.
     * @return the EducationalQualification
     */
    public String getEducationalQualification() {
        return (String)getAttributeInternal(EDUCATIONALQUALIFICATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for EducationalQualification.
     * @param value value to set the EducationalQualification
     */
    public void setEducationalQualification(String value) {
        setAttributeInternal(EDUCATIONALQUALIFICATION, value);
    }

    /**
     * Gets the attribute value for Subject, using the alias name Subject.
     * @return the Subject
     */
    public String getSubject() {
        return (String)getAttributeInternal(SUBJECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Subject.
     * @param value value to set the Subject
     */
    public void setSubject(String value) {
        setAttributeInternal(SUBJECT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getSubjectEO() {
        return (EntityImpl)getAttributeInternal(SUBJECTEO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setSubjectEO(EntityImpl value) {
        setAttributeInternal(SUBJECTEO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTeacherClassEO() {
        return (RowIterator)getAttributeInternal(TEACHERCLASSEO);
    }

    /**
     * @param staffId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number staffId) {
        return new Key(new Object[]{staffId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model_Entity.StaffEO");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl se = new SequenceImpl("STAFF_SEQ",getDBTransaction());
        this.setStaffId(se.getSequenceNumber());
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
